@startuml
set namespaceSeparator ::

abstract class "file:::::::D:::fredgrttsstuff::GithubProjects::not_in_flutter_docs::dart_language_guides::composite::bin::composite.dart::Thing" {
  +String name
  +void doSomething()
}

class "file:::::::D:::fredgrttsstuff::GithubProjects::not_in_flutter_docs::dart_language_guides::composite::bin::composite.dart::CompositeThing" {
  +String name
  -Set<Thing> _childThings
  +void addChild()
  +void doSomething()
}

"file:::::::D:::fredgrttsstuff::GithubProjects::not_in_flutter_docs::dart_language_guides::composite::bin::composite.dart::Thing" <|-- "file:::::::D:::fredgrttsstuff::GithubProjects::not_in_flutter_docs::dart_language_guides::composite::bin::composite.dart::CompositeThing"

class "file:::::::D:::fredgrttsstuff::GithubProjects::not_in_flutter_docs::dart_language_guides::composite::bin::composite.dart::LeafThing" {
  +String name
  +void doSomething()
}

"file:::::::D:::fredgrttsstuff::GithubProjects::not_in_flutter_docs::dart_language_guides::composite::bin::composite.dart::Thing" <|-- "file:::::::D:::fredgrttsstuff::GithubProjects::not_in_flutter_docs::dart_language_guides::composite::bin::composite.dart::LeafThing"


@enduml